#!/bin/sh
# Publish a Homebrew formula for this release into the tap repository.
#
# A tap is just a GitHub repo named homebrew-<name> holding formula files, so
# `brew install carlallenn/tap/iiif-server` resolves to
# github.com/CarlAllenn/homebrew-tap :: Formula/iiif-server.rb.
#
# Skipped cleanly when TAP_TOKEN is absent, so the release does not fail on an
# optional distribution channel that has not been set up. The formula is
# generated from the checksums this release actually produced — never
# hand-edited, because a formula whose sha256 does not match the release is a
# broken install for everyone who taps it.
set -eu

cd "$(dirname "$0")/../.."

: "${GITHUB_REF:?}"
: "${GITHUB_REPOSITORY:?}"

if [ -z "${TAP_TOKEN:-}" ]; then
  echo "TAP_TOKEN not set — skipping the Homebrew tap."
  echo "  To enable: create github.com/CarlAllenn/homebrew-tap and add a PAT"
  echo "  with contents:write on it as the TAP_TOKEN secret."
  exit 0
fi

tag=${GITHUB_REF#refs/tags/}
version=${tag#v}
base="https://github.com/${GITHUB_REPOSITORY}/releases/download/${tag}"

sum_for() {
  file="iiif-server-${tag}-$1.tar.gz"
  if [ ! -f "dist/${file}.sha256" ]; then
    echo "FAIL: no checksum for $1; refusing to write a formula that cannot install" >&2
    exit 1
  fi
  cut -d' ' -f1 < "dist/${file}.sha256"
}

arm_mac=$(sum_for aarch64-apple-darwin)
intel_mac=$(sum_for x86_64-apple-darwin)
arm_linux=$(sum_for aarch64-unknown-linux-musl)
intel_linux=$(sum_for x86_64-unknown-linux-musl)

work=$(mktemp -d)
trap 'rm -rf "${work}"' EXIT

git clone --depth 1 \
  "https://x-access-token:${TAP_TOKEN}@github.com/CarlAllenn/homebrew-tap.git" \
  "${work}/tap"

mkdir -p "${work}/tap/Formula"
cat > "${work}/tap/Formula/iiif-server.rb" << FORMULA
# Generated by the release pipeline. Do not edit by hand: the checksums must
# match the published release exactly.
class IiifServer < Formula
  desc "Complete, correct IIIF Image API 3.0 and 2.1 server in one static binary"
  homepage "https://github.com/${GITHUB_REPOSITORY}"
  version "${version}"
  license "AGPL-3.0-only"

  on_macos do
    on_arm do
      url "${base}/iiif-server-${tag}-aarch64-apple-darwin.tar.gz"
      sha256 "${arm_mac}"
    end
    on_intel do
      url "${base}/iiif-server-${tag}-x86_64-apple-darwin.tar.gz"
      sha256 "${intel_mac}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/iiif-server-${tag}-aarch64-unknown-linux-musl.tar.gz"
      sha256 "${arm_linux}"
    end
    on_intel do
      url "${base}/iiif-server-${tag}-x86_64-unknown-linux-musl.tar.gz"
      sha256 "${intel_linux}"
    end
  end

  def install
    bin.install "iiif-server"
  end

  test do
    assert_match "iiif-server #{version}", shell_output("#{bin}/iiif-server --version")
  end
end
FORMULA

cd "${work}/tap"
git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git add Formula/iiif-server.rb
if git diff --cached --quiet; then
  echo "formula already current for ${tag}"
  exit 0
fi
git commit -m "iiif-server ${version}"
git push
echo "published the Homebrew formula for ${version}"
